
version: 2
jobs:
  deploy-job:
  steps:
    - checkout
    - run:
      name: Deploy Master to Heroku
      command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-job:
          filters:
            branches:
              only: master
